group_work_one/group_work_one/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('joulukortti.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

group_work_one/joulukortti/urls.py
from django.urls import path
from . import views
from .views import ColorListView, ColorCreateView, ColorUpdateView, ColorDeleteView


urlpatterns = [
    path('', views.home, name='home'),
    path('canvas/', views.canvas, name='canvas'),
    path('gallery/', views.gallery, name='gallery'),
    path('save_drawing/', views.save_drawing, name='save_drawing'),
    path('colors/', ColorListView.as_view(), name='color_list'),
    path('colors/add/', ColorCreateView.as_view(), name='color_add'),
    path('colors/<int:pk>/edit/', ColorUpdateView.as_view(), name='color_edit'),
    path('colors/<int:pk>/delete/', ColorDeleteView.as_view(), name='color_delete'),
]

group_work_one/users/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

group_work_one/joulukortti/models.py
import os

from django.db import models
from django.contrib.auth.models import User

class XmasCard(models.Model):
    name = models.CharField(max_length=255)
    date_created = models.DateTimeField(auto_now_add=True)
    drawing = models.ImageField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}"

class Color(models.Model):
    name = models.CharField(max_length=100)
    hex_value = models.CharField(max_length=7)  # To store values like '#ffffff'
    users = models.ManyToManyField(User, blank=True)  # Association with users

    def __str__(self):
        return self.name

group_work_one/users/models.py
from django.db import models

# Create your models here.

group_work_one/joulukortti/templates/joulukortti/forms.py
from django import forms

from joulukortti.models import Color


class AddColorToPaletteForm(forms.Form):
    available_colors = forms.ModelMultipleChoiceField(
        queryset=Color.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

group_work_one/joulukortti/views.py
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Color
from django.contrib.auth.mixins import LoginRequiredMixin

import json
from django.http import HttpResponse
from django.shortcuts import render

import os
from django.core.files import File
import base64
import uuid
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.files.base import ContentFile
from .models import XmasCard


def home(request):
    return render(request, 'joulukortti/home.html')

def canvas(request):
    if request.user.is_authenticated:
        colors = request.user.color_set.all()  # Get colors specific to the user
    else:
        # Get all unique color objects for unauthenticated users
        colors = Color.objects.values('hex_value').annotate(count=Count('id')).order_by()
    return render(request, 'joulukortti/canvas.html', {'colors': colors})

@login_required
def gallery(request):
    xmas_cards = XmasCard.objects.all()
    return render(request, 'joulukortti/gallery.html', {'xmas_cards': xmas_cards})


@csrf_exempt
def save_drawing(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            name = data['name']
            image_data = data['image']

            # Decode the base64 image
            format, imgstr = image_data.split(';base64,')
            ext = format.split('/')[-1]

            # Use the drawing's name for the file name, replacing spaces with underscores and adding the extension
            filename = f"{name.replace(' ', '_')}.{ext}"

            # Ensure filename uniqueness to avoid overwriting existing files
            filename = get_unique_filename(filename)

            image = ContentFile(base64.b64decode(imgstr), name=filename) # name=f'{uuid.uuid4()}.{ext}'

            # For simplicity, create a user if it doesn't exist
            user, created = User.objects.get_or_create(username='December') # Replace with appropriate username

            # Create a new XmasCard instance
            xmas_card = XmasCard(name=name, drawing=image, user=user)
            xmas_card.save()

            return JsonResponse({'status': 'success'})
        except Exception as e:
            return JsonResponse({'status': 'error', 'message': str(e)}, status=500)
    else:
        return JsonResponse({'status': 'error'}, status=400)

def get_unique_filename(filename):
    """
    Generates a unique filename by appending a counter to the filename
    if a file with the same name already exists.
    """
    original_filename = filename
    counter = 1
    while os.path.exists(os.path.join('/', filename)):  # Replace with your media directory
        name, ext = os.path.splitext(original_filename)
        filename = f"{name}_{counter}{ext}"
        counter += 1
    return filename

class ColorListView(LoginRequiredMixin, ListView):
    model = Color
    template_name = 'joulukortti/colors/color_list.html'

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return Color.objects.filter(users=self.request.user)
        else:
            return Color.objects.none()

class ColorCreateView(LoginRequiredMixin, CreateView):
    model = Color
    fields = ['name', 'hex_value']
    template_name = 'joulukortti/colors/color_form.html'
    success_url = reverse_lazy('color_list')

    def form_valid(self, form):
        color = form.save(commit=False)
        color.save()
        color.users.add(self.request.user)  # Link color to the current user
        return super().form_valid(form)

class ColorUpdateView(LoginRequiredMixin, UpdateView):
    model = Color
    fields = ['name', 'hex_value']
    template_name = 'joulukortti/colors/color_form.html'
    success_url = reverse_lazy('color_list')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(users=self.request.user)

class ColorDeleteView(LoginRequiredMixin, DeleteView):
    model = Color
    template_name = 'joulukortti/colors/color_confirm_delete.html'
    success_url = reverse_lazy('color_list')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(users=self.request.user)

group_work_one/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

from joulukortti.models import Color


def register(request):
    """Register a new user."""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)

            # Assign all colors to the new user
            all_colors = Color.objects.all()
            for color in all_colors:
                color.users.add(new_user)

            return redirect('home')
    
    context = {'form': form}
    return render(request, 'registration/register.html', context)
        

group_work_one/joulukortti/templates/joulukortti/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
    {% load static %}
     <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>{% block title %}My Django App{% endblock %}</title>


        <!-- Block for additional CSS -->
    {% block extra_css %}{% endblock %}
    <!-- Common CSS, JavaScript, etc. -->
</head>
<body>
    <header>
        <!-- Site header content -->
    </header>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="{% static 'lg.jpg' %}" alt="Logo" height="100"> <!-- Adjust height as needed -->
            </a>
            <div class="navbar-nav">
                {% if request.path != '/' %}
                <a href="{% url 'home' %}" class="nav-link active text-uppercase fw-bold rounded" aria-current="page">Go Home</a>&nbsp;&nbsp;
                {% endif %}
                {% if request.path != '/canvas/' and request.path != '/' %}
                <a class="nav-link text-uppercase fw-bold rounded" href="{% url 'canvas' %}" >Go to Canvas</a> &nbsp;
                {% endif %}
                {% if user.is_authenticated %}
                <form action="{% url 'users:logout' %}" method='post'>
                    {% csrf_token %}
                    <button class="btn btn-secondary">Log out</button>
                </form>
                {% else %}

                    <a class="nav-link text-uppercase fw-bold" href="{% url 'users:register' %}">Register</a>
                &nbsp;
                    <a class="nav-link text-uppercase fw-bold" href="{% url 'users:login' %}">Log in</a>
                {% endif %}
            </div>
        </div>
    </nav>

    <main>
        {% block content %}
        <!-- Default content (can be empty) -->
        {% endblock %}
    </main>

    <footer>
        <!-- Site footer content -->
    </footer>
<!-- Bootstrap JS Bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

group_work_one/joulukortti/templates/joulukortti/canvas.html
<!-- canvas.html -->
{% extends 'joulukortti/base.html' %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/canvas.css' %}">
{% endblock %}

{% block title %}Canvas Drawing App with Color Picker{% endblock %}

{% block content %}
<div class="container mt-3">
    <div class="row align-items-center m-3">
        <div class="col-auto whiteBackground rounded">
            <label for="drawingName" class="col-form-label">Drawing Name:</label>
        </div>
        <div class="col-5">
            <input type="text" class="form-control" id="drawingName" name="drawingName" required>
        </div>
    </div>


    <div class="d-flex">
        <canvas id="drawingCanvas" width="800" height="400" class="me-3"></canvas>

        <div class="d-flex flex-column">
            <div class="whiteBackground rounded px-2 pt-2 text-center text-uppercase">Background colors</div>

            <div class="whiteBackground p-4 d-inline-block rounded mb-4">
                <div class="row mb-3">
                {% for color in colors %}
                    <div class="col-3 background-color colorSwatch" style="background-color: {{ color.hex_value }}" data-color="{{ color.hex_value }}"></div>

                    {% if forloop.counter|divisibleby:4 and not forloop.last %}
                        </div><div class="row mb-3">
                    {% endif %}
                {% endfor %}
                </div>
            </div>

            <div class="whiteBackground rounded px-2 pt-2 text-center text-uppercase">Line colors</div>
            <div class="whiteBackground p-4 d-inline-block rounded mb-4">
                <div class="row mb-3">
                {% for color in colors %}
                    <div class="col-3 line-color colorSwatch" style="background-color: {{ color.hex_value }}" data-color="{{ color.hex_value }}"></div>

                    {% if forloop.counter|divisibleby:4 and not forloop.last %}
                        </div><div class="row mb-3">
                    {% endif %}
                {% endfor %}
                </div>
            </div>
        </div>

        <div class="ms-3 align-self-end d-flex flex-column">

            <button id="downloadBtn" class="btn btn-primary m-2">Download Drawing</button>
            {% if user.is_authenticated %}
                <a class="btn btn-info m-2" href="{% url 'color_list' %}">Modify Colors</a>
                <button id="saveDrawing" data-url="{% url 'save_drawing' %}" class="btn btn-secondary m-2">
                Save Drawing
                </button>
            {% endif %}
        </div>

    </div>

    <button id="saveDrawing" data-url="{% url 'save_drawing' %}" class="btn btn-secondary m-2">
       Save Drawing
    </button>

    <button id="undoButton" class="btn-secondary">Undo</button>

    <button id="clearCanvas" class="btn btn-secondary m-2" onclick="window.location.reload()">Clear</button>
    <br/>
    <div class="dropMenu">
        <button id="linewidthMenu" class="dropMenuBtn">Linewidth</button>
        <div class="dropMenuContent">
            <button class="lineWidthBtn" data-size="1">1</button>
            <button class="lineWidthBtn" data-size="2">2</button>
            <button class="lineWidthBtn" data-size="3">3</button>
            <button class="lineWidthBtn" data-size="4">4</button>
            <button class="lineWidthBtn" data-size="5">5</button>
            <button class="lineWidthBtn" data-size="6">6</button>
            <button class="lineWidthBtn" data-size="7">7</button>
            <button class="lineWidthBtn" data-size="8">8</button>
            <button class="lineWidthBtn" data-size="9">9</button>
        </div>
    </div>
</div>


  <!-- Script for Canvas Drawing -->
  <script src="{% static 'js/canvas-drawing.js' %}"></script>

  <!-- Script for Color Picker -->
  <script src="{% static 'js/color-picker.js' %}"></script>

  <!-- Script for Download Functionality -->
  <script src="{% static 'js/download-drawing.js' %}"></script>

    <!-- Script for Save Functionality -->
    <script src="{% static 'js/save-drawing.js' %}"></script>
{% endblock %}

group_work_one/joulukortti/templates/joulukortti/colors/color_confirm_delete.html
<!-- Confirm delete -->
{% extends 'joulukortti/base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block title %}Confirm on Delete Color{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <p id="confirm">Are you sure you want to delete "{{ object.name }}"?</p>
    <button type="submit">Confirm</button>
</form>
{% endblock %}

group_work_one/joulukortti/templates/joulukortti/colors/color_form.html
<!-- Form for creating and editing a color -->
{% extends 'joulukortti/base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block title %}Edit Color{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>

<!--<form method="post">
    {% csrf_token %}
    {{ add_color_form.as_p }}
    <button type="submit">Add Selected Colors</button>
</form>-->
{% endblock %}

group_work_one/joulukortti/templates/joulukortti/colors/color_list.html
<!-- List all colors -->
{% extends 'joulukortti/base.html' %}
{% load static %}

{% block title %}List of Colors{% endblock %}

{% block content %}

<table class="table" style="width: 50%; margin-left: auto; margin-right: auto;">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Color</th>
            <th scope="col">Name</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for color in object_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>
                    <div style="width: 30px; height: 30px; background-color: {{ color.hex_value }};"></div>
                </td>
                <td class="fw-bold text-uppercase">{{ color.name }}</td>
                <td>
                    <a href="{% url 'color_edit' color.id %}" class="btn btn-primary btn-sm">Edit</a>
                    <a href="{% url 'color_delete' color.id %}" class="btn btn-danger btn-sm">Delete</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<div class="p-3" style="display: flex; justify-content: center;">
<a href="{% url 'color_add' %}" class="btn btn-success btn-sm">Add New Color</a>
</div>
{% endblock %}

group_work_one/joulukortti/templates/joulukortti/gallery.html
<!-- gallery.html -->
{% extends 'joulukortti/base.html' %}
{% load static %}

{% block title %}Gallery{% endblock %}

{% block content %}
<div class="container">
    <h2 class="whiteBackground p-3 rounded text-center">All Christmas Cards</h2>
    <a class="button btn-light rounded p-1 text-decoration-none text-uppercase">Click on an image to dowload it</a>
    <div class="row">
    {% for card in xmas_cards %}
        <div class="col-6 my-4">
        <div>
            <h3 class="whiteBackground rounded text-center">{{ card.name }}</h3>

            {% if card.drawing %}
                <a href="{{ card.drawing.url }}" download>
                    <img src="{{ card.drawing.url }}" alt="{{ card.name }} Drawing" class="img-fluid">
                </a>
            {% else %}
                <p>No drawing available</p>
            {% endif %}
            <p class="whiteBackground rounded pl-3">Created on: {{ card.date_created }}</p>
        </div>
        </div>
    {% endfor %}
    </div>
</div>

{% endblock %}

group_work_one/joulukortti/templates/joulukortti/home.html
<!-- home.html -->
{% extends 'joulukortti/base.html' %}
{% load static %}

{% block title %}Home Page{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="whiteBackground p-3 rounded d-inline-block">Welcome to the Home Page,
    {% if user.is_authenticated %}
    {{ user.username }}!
    {% else %}
        Guest!
    {% endif %}
    </h1>
    <br>
    <a href="{% url 'canvas' %}" class="btn btn-primary mb-1">
        {% if user.is_authenticated %}
            Go to Canvas
        {% else %}
            Proceed as a guest (Go to Canvas)
        {% endif %}
    </a>
    <br>
    <a href="{% url 'gallery' %}" class="btn btn-info mb-1">
        Go to Gallery
    </a>
        <br>

</div>
{% endblock %}